# This version should be updated whenever we update the version of the Rust
# standard library we currently track.

[toolchain]
channel = "2025-02-10"
components = ["llvm-tools-preview", "rustc-dev", "rust-src", "rustfmt"]
